version: '3'

services:
  flask:
    build : .
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./FlaskApp:/app
    working_dir: /app
    depends_on:
      - mongo 
    environment:
      - MONGO_URI=mongodb://mongo:27017/azure-function-testing
      - HOST=0.0.0.0
      - PORT=5000

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
